#include "sb53/GcodeRewriter.hpp"
#include "sb53/GcodeScanner.hpp"
#include "sb53/TemperaturePlanner.hpp"
#include "sb53/Version.hpp"

#include <catch2/catch_approx.hpp>
#include <catch2/catch_test_macros.hpp>

#include <numbers>
#include <sstream>

using namespace sb53;
using Catch::Approx;

namespace {

FilamentProfile testFilament()
{
    FilamentProfile f;
    f.name = "test"; f.type = "PLA";
    f.lowFlow = 1.0;   f.lowTemp = 190.0;
    f.midFlow = 15.0;  f.midTemp = 220.0;
    f.highFlow = 22.0; f.highTemp = 235.0;
    f.speedQualityBias = 5;
    return f;
}

ExtruderProfile testExtruder()
{
    ExtruderProfile e;
    e.tempRise = 10.0; e.tempRiseTime = 1.0;
    e.tempFall = 5.0;  e.tempFallTime = 1.0;
    e.smoothingWindow = 1;
    e.startMacro = "PRINT_START";
    e.temperatureToken = "EXTRUDER_TEMP";
    return e;
}

// A tiny but structurally complete file that exercises the rewrite paths.
constexpr std::string_view kSource =
    "; HEADER_BLOCK_START\n"                    // 1
    "; generated by OrcaSlicer 2.4.2\n"         // 2
    "; HEADER_BLOCK_END\n"                      // 3
    "PRINT_START EXTRUDER_TEMP=295 BED_TEMP=65\n"  // 4
    "M83\n"                                     // 5
    ";HEIGHT:0.25\n"                            // 6  <- body starts
    ";WIDTH:0.5\n"                              // 7
    ";TYPE:Inner wall\n"                        // 8
    "G1 F9000\n"                                // 9  fast: should be clamped
    "G1 X10 Y10 E1.0\n"                         // 10
    "G1 X20 Y20 E1.0\n"                         // 11
    ";TYPE:Sparse infill\n"                     // 12
    "G1 F600\n"                                 // 13 slow: should be kept
    "G1 X30 Y30 E1.0\n"                         // 14
    "G1 E-2 F1800\n"                            // 15 retraction
    "; EXECUTABLE_BLOCK_END\n"                  // 16 <- body ends at 15
    "; filament_type = PLA\n";                  // 17

struct Harness {
    ScanResult      scan;
    SourceAnalysis  analysis;
    TemperaturePlan plan;
    DiagnosticList  diagnostics;
    NullProgressSink progress;

    Harness()
    {
        std::istringstream in{std::string(kSource)};
        scan = GcodeScanner::scan(in, diagnostics);

        // A flat, generous plan so feedrate clamping is the variable under test.
        analysis.seconds = {
            FlowSecond{1.0, 8.0, 10.0, 0.5},
            FlowSecond{2.0, 8.0, 10.0, 2.0},
            FlowSecond{3.0, 8.0, 10.0, 10.0},
        };
        plan.achievableTemperature = {205.0, 205.0, 205.0};
        plan.desiredTemperature = plan.achievableTemperature;
        plan.blendedFlow = {8.0, 8.0, 8.0};
        plan.smoothedFlow = plan.blendedFlow;
        plan.initialTemperature = 205.0;
        plan.minTemperature = 205.0;
        plan.maxTemperature = 205.0;
    }

    std::string run(RewriteOptions options = {})
    {
        std::istringstream in{std::string(kSource)};
        std::ostringstream out;
        stats = rewriteGcode(in, out, scan, analysis, plan, testExtruder(),
                             testFilament(), diagnostics, progress, options);
        return out.str();
    }

    RewriteStats stats;
};

bool contains(const std::string& haystack, std::string_view needle)
{
    return haystack.find(needle) != std::string::npos;
}

std::size_t count(const std::string& haystack, std::string_view needle)
{
    std::size_t n = 0;
    for (std::size_t pos = haystack.find(needle); pos != std::string::npos;
         pos = haystack.find(needle, pos + needle.size())) {
        ++n;
    }
    return n;
}

} // namespace

TEST_CASE("extrusion cross-section geometry", "[rewriter][geometry]")
{
    // A rectangle with semicircular ends: h*(w-h) + pi*(h/2)^2. ALGORITHM.md §7.
    const double h = 0.2;
    const double w = 0.45;
    CHECK(detail::extrusionArea(h, w) ==
          Approx(h * (w - h) + std::numbers::pi * (h / 2) * (h / 2)));

    SECTION("degenerate inputs yield zero rather than an infinite feedrate") {
        CHECK(detail::extrusionArea(0.0, 0.4) == 0.0);
        CHECK(detail::extrusionArea(0.2, 0.0) == 0.0);
        CHECK(detail::extrusionArea(-1.0, 0.4) == 0.0);
        // A bead narrower than it is tall is not physically meaningful.
        CHECK(detail::extrusionArea(0.5, 0.2) == 0.0);
    }

    SECTION("feedrate conversion") {
        // 60 * flow / area, because F words are per minute and flow is per second.
        const double area = detail::extrusionArea(0.2, 0.4);
        CHECK(detail::flowToFeedrate(10.0, area) == Approx(60.0 * 10.0 / area));
        CHECK(detail::flowToFeedrate(10.0, 0.0) == 0.0);
        CHECK(detail::flowToFeedrate(0.0, area) == 0.0);
    }
}

TEST_CASE("G-code word extraction", "[rewriter][parse]")
{
    using detail::word;

    CHECK(word("G1 X10 Y20 E1.5 F3000", 'E') == Approx(1.5));
    CHECK(word("G1 X10 Y20 E1.5 F3000", 'F') == Approx(3000.0));
    CHECK(word("G1 E-2 F1800", 'E') == Approx(-2.0));
    CHECK(word("G1 X10 Y10 E.10057", 'E') == Approx(0.10057));

    SECTION("comments are ignored") {
        CHECK_FALSE(word("G1 X10 ; E5 in a comment", 'E').has_value());
        CHECK(word("G1 F1800    ; Reset Speed", 'F') == Approx(1800.0));
    }

    SECTION("a letter mid-token is not a word") {
        CHECK_FALSE(word("PRINT_START EXTRUDER_TEMP=295", 'E').has_value());
    }

    SECTION("missing words") {
        CHECK_FALSE(word("G1 X10 Y10", 'E').has_value());
    }
}

TEST_CASE("number formatting is locale-invariant and drops trailing zeros",
          "[rewriter][format]")
{
    using detail::formatNumber;

    CHECK(formatNumber(212.7, 1) == "212.7");
    CHECK(formatNumber(213.0, 1) == "213");        // not "213.0"
    CHECK(formatNumber(5918.0, 0) == "5918");
    CHECK(formatNumber(0.0432, 4) == "0.0432");
    CHECK(formatNumber(0.0, 1) == "0");
    CHECK(formatNumber(-1.5, 1) == "-1.5");

    // Always a '.' separator regardless of the machine's locale -- G-code has no other
    // form, and locale-dependence is what broke the legacy (known-bugs.md #5).
    CHECK(formatNumber(1.5, 1).find(',') == std::string::npos);
}

TEST_CASE("feature type markers", "[rewriter][parse]")
{
    using detail::parseFeatureType;

    CHECK(parseFeatureType("Inner wall") == FeatureType::InnerWall);
    CHECK(parseFeatureType("Sparse infill") == FeatureType::SparseInfill);
    CHECK(parseFeatureType("Internal solid infill") == FeatureType::InternalSolidInfill);
    CHECK(parseFeatureType("Support") == FeatureType::Support);
    CHECK(parseFeatureType("Outer wall") == FeatureType::OuterWall);
    CHECK(parseFeatureType("Something new") == FeatureType::Unknown);

    // PrusaSlicer spellings
    CHECK(parseFeatureType("External perimeter") == FeatureType::OuterWall);
    CHECK(parseFeatureType("Solid infill") == FeatureType::InternalSolidInfill);
}

TEST_CASE("speed is clamped down but never up", "[rewriter][safety]")
{
    // THE core safety property (ALGORITHM.md §2). The tool must never make a print more
    // aggressive than the user's own profile asked for.
    Harness h;
    const std::string out = h.run();

    CHECK(contains(out, kCommentRecommendedSpeed));   // the fast line was reduced
    CHECK(contains(out, kCommentKeepSlicerSpeed));    // the slow line was left alone
    CHECK(h.stats.feedratesReduced >= 1);

    SECTION("the reduced feedrate is genuinely lower than the slicer's") {
        // The source asks for F9000 on an inner wall at 0.25 x 0.5 mm.
        std::istringstream lines{out};
        std::string line;
        while (std::getline(lines, line)) {
            if (line.find(kCommentRecommendedSpeed) != std::string::npos) {
                const auto f = detail::word(line, 'F');
                REQUIRE(f.has_value());
                CHECK(*f < 9000.0);
                CHECK(*f > 0.0);
            }
        }
    }

    SECTION("a slow slicer feedrate is preserved exactly") {
        CHECK(contains(out, "G1 F600    " + std::string(kCommentKeepSlicerSpeed)));
    }
}

TEST_CASE("temperature commands are emitted as the plan changes", "[rewriter]")
{
    Harness h;
    // A plan that actually moves, so commands must appear.
    h.plan.achievableTemperature = {195.0, 215.0, 230.0};
    h.plan.initialTemperature = 195.0;

    const std::string out = h.run();

    CHECK(h.stats.temperatureCommands > 0);
    CHECK(contains(out, "M104 S"));

    SECTION("one decimal place, no trailing zero") {
        CHECK_FALSE(contains(out, "M104 S195.0"));
    }
}

TEST_CASE("the start macro temperature is replaced by parsing, not splicing",
          "[rewriter][safety]")
{
    // The legacy splices at a fixed offset assuming exactly three digits, corrupting the
    // line for 2- and 4-digit temperatures (known-bugs.md #4).
    Harness h;

    SECTION("three-digit original") {
        const std::string out = h.run();
        CHECK(contains(out, "PRINT_START EXTRUDER_TEMP=205 BED_TEMP=65"));
        CHECK(contains(out, kCommentResetInitialTemperature));
        CHECK_FALSE(contains(out, "EXTRUDER_TEMP=295"));
    }

    SECTION("a two-digit replacement does not corrupt the rest of the line") {
        h.plan.initialTemperature = 95.0;
        const std::string out = h.run();
        CHECK(contains(out, "PRINT_START EXTRUDER_TEMP=95 BED_TEMP=65"));
    }

    SECTION("a four-digit-ish replacement does not truncate") {
        h.plan.initialTemperature = 205.5;
        const std::string out = h.run();
        CHECK(contains(out, "PRINT_START EXTRUDER_TEMP=205.5 BED_TEMP=65"));
    }
}

TEST_CASE("the output is marked so it cannot be processed twice", "[rewriter][safety]")
{
    Harness h;
    const std::string out = h.run();

    CHECK(contains(out, kProcessedMarker));

    // And the scanner must actually refuse the result.
    std::istringstream again{out};
    DiagnosticList d;
    const auto rescan = GcodeScanner::scan(again, d);
    CHECK(rescan.alreadyProcessed);
    CHECK(d.hasErrors());
}

TEST_CASE("content outside the print body is copied through untouched", "[rewriter]")
{
    Harness h;
    const std::string out = h.run();

    CHECK(contains(out, "; generated by OrcaSlicer 2.4.2"));
    CHECK(contains(out, "; EXECUTABLE_BLOCK_END"));
    CHECK(contains(out, "; filament_type = PLA"));
}

TEST_CASE("retractions keep the slicer's feedrate", "[rewriter]")
{
    // A retraction is not a printing move; applying a flow-derived feedrate to it would
    // be meaningless.
    Harness h;
    const std::string out = h.run();
    CHECK(contains(out, "G1 E-2 F1800"));
}

TEST_CASE("unretracts do not advance the filament coordinate", "[rewriter][safety]")
{
    // Regression: the rewriter's filament counter MUST track the analyser's exactly.
    //
    // MoveDumpParser zeroes both the retract and its matching unretract, so counting
    // unretracts here makes the rewriter run ahead of the plan. Because the plan holds
    // its last value past the end, the symptom is not a crash but silence -- temperature
    // commands stop partway through the print and everything after runs at a fixed
    // temperature.
    //
    // Differential comparison against the legacy caught this: the plan spanned 3475 mm
    // while the rewriter had already reached 5616 mm on the same file.

    const std::string_view source =
        "M83\n"
        ";HEIGHT:0.25\n"
        ";WIDTH:0.5\n"
        "G1 X10 Y10 E1.0\n"    // real extrusion: counts
        "G1 E-2 F1800\n"       // retract: must not count
        "G1 E2 F1800\n"        // unretract: must not count either
        "G1 X20 Y20 E1.0\n"    // real extrusion: counts
        "; EXECUTABLE_BLOCK_END\n";

    DiagnosticList d;
    NullProgressSink p;

    std::istringstream scanIn{std::string(source)};
    const auto scan = GcodeScanner::scan(scanIn, d);

    SourceAnalysis analysis;
    // The plan covers exactly 2 mm -- the true extrusion. If unretracts were counted the
    // rewriter would reach 4 mm and fall off the end.
    analysis.seconds = {FlowSecond{1.0, 5.0, 6.0, 1.0},
                        FlowSecond{2.0, 5.0, 6.0, 2.0}};

    TemperaturePlan plan;
    plan.achievableTemperature = {200.0, 230.0};
    plan.initialTemperature = 200.0;
    plan.minTemperature = 200.0;
    plan.maxTemperature = 230.0;

    std::istringstream in{std::string(source)};
    std::ostringstream out;
    const auto stats = rewriteGcode(in, out, scan, analysis, plan, testExtruder(),
                                    testFilament(), d, p, {});

    // The second real extrusion lands at 2 mm, the top of the plan, so the temperature
    // must reach 230 -- not be stuck at whatever the coordinate overshot to.
    CHECK(contains(out.str(), "M104 S230"));
    CHECK(stats.temperatureCommands >= 2);
}

TEST_CASE("pressure advance is gated by feature and by profile", "[rewriter][pa]")
{
    Harness h;
    h.plan.achievableTemperature = {195.0, 215.0, 230.0};

    SECTION("off unless explicitly enabled") {
        RewriteOptions o;
        o.adjustPressureAdvance = false;
        const std::string out = h.run(o);
        CHECK(count(out, "SET_PRESSURE_ADVANCE") == 0);
        CHECK(h.stats.pressureAdvanceCommands == 0);
    }

    SECTION("still off when the option is on but the filament profile says no") {
        // Both switches must agree: the option is a firmware capability, the profile
        // flag is the user's choice.
        RewriteOptions o;
        o.adjustPressureAdvance = true;
        const std::string out = h.run(o);   // testFilament() has the flag false
        CHECK(count(out, "SET_PRESSURE_ADVANCE") == 0);
    }
}

TEST_CASE("a missing plan is refused rather than silently passed through",
          "[rewriter][safety]")
{
    // The legacy's defining failure was writing a file that looked processed but was not
    // (known-bugs.md #11).
    Harness h;
    h.plan = TemperaturePlan{};

    std::istringstream in{std::string(kSource)};
    std::ostringstream out;
    DiagnosticList d;
    NullProgressSink p;
    const auto stats = rewriteGcode(in, out, h.scan, h.analysis, h.plan, testExtruder(),
                                    testFilament(), d, p, {});

    CHECK(d.hasErrors());
    CHECK(stats.linesWritten == 0);
}
