#include "sb53/GcodeScanner.hpp"
#include "sb53/Version.hpp"

#include <catch2/catch_test_macros.hpp>

#include <filesystem>
#include <fstream>
#include <sstream>

using namespace sb53;

namespace {

ScanResult scanText(std::string_view text, DiagnosticList& diags)
{
    std::istringstream in{std::string(text)};
    return GcodeScanner::scan(in, diags);
}

bool hasCode(const DiagnosticList& diags, Code c)
{
    for (const auto& d : diags) {
        if (d.code == c) {
            return true;
        }
    }
    return false;
}

// A minimal but structurally complete file: header, body markers, footer metadata.
constexpr std::string_view kMinimal =
    "; HEADER_BLOCK_START\n"
    "; generated by OrcaSlicer 2.4.2\n"
    "; HEADER_BLOCK_END\n"
    "; EXECUTABLE_BLOCK_START\n"
    "PRINT_START EXTRUDER_TEMP=295 BED_TEMP=65\n"
    "M83 ; use relative distances for extrusion\n"
    ";HEIGHT:0.25\n"
    ";TYPE:Skirt\n"
    "G1 X54.553 Y34.617 E.10057\n"
    "; EXECUTABLE_BLOCK_END\n"
    "; filament_type = PLA\n"
    "; filament_settings_id = \"Elegoo HS PLA+ awd hott\"\n"
    "; printer_settings_id = AWD V0 @ 0.4 nozzle\n";

} // namespace

TEST_CASE("scanner accepts a well-formed file", "[scanner]")
{
    DiagnosticList diags;
    const auto r = scanText(kMinimal, diags);

    CHECK_FALSE(diags.hasErrors());
    CHECK(r.extrusionMode == ExtrusionMode::Relative);
    CHECK_FALSE(r.alreadyProcessed);
    CHECK(r.hasPrintBody());
    CHECK(r.totalLines == 13);
}

TEST_CASE("print body bounds are asymmetric", "[scanner][bounds]")
{
    // The line that MARKS the start is part of the body; the line that marks the end is
    // not. This asymmetry is inherited deliberately -- getting it wrong shifts every
    // downstream artefact by one line. See docs/legacy/algorithm-map.md.

    DiagnosticList diags;
    const auto r = scanText(kMinimal, diags);

    CHECK(r.bodyFirstLine == 7);   // the ";HEIGHT:0.25" line itself
    CHECK(r.bodyLastLine == 9);    // the G1 move; NOT the "; EXECUTABLE_BLOCK_END" at 10
}

TEST_CASE("scanner recognises PrusaSlicer-style markers", "[scanner][bounds]")
{
    DiagnosticList diags;
    const auto r = scanText(
        "M83\n"
        "; Z_HEIGHT: 0.25\n"
        "G1 X10 Y10 E.5\n"
        "; PRINT_END\n",
        diags);

    CHECK_FALSE(diags.hasErrors());
    CHECK(r.bodyFirstLine == 2);
    CHECK(r.bodyLastLine == 3);
}

TEST_CASE("extrusion mode preconditions", "[scanner][precondition]")
{
    // ALGORITHM.md §9. Absolute extrusion makes the whole flow model meaningless, and
    // the legacy never checked -- producing silently wrong output
    // (legacy/known-bugs.md #9).

    SECTION("M83 is accepted") {
        DiagnosticList diags;
        const auto r = scanText(kMinimal, diags);
        CHECK(r.extrusionMode == ExtrusionMode::Relative);
        CHECK_FALSE(hasCode(diags, Code::AbsoluteExtrusionUnsupported));
    }

    SECTION("M82 is rejected") {
        DiagnosticList diags;
        const auto r = scanText("M82\n;HEIGHT:0.2\nG1 X1 E1\n; PRINT_END\n", diags);
        CHECK(r.extrusionMode == ExtrusionMode::Absolute);
        CHECK(hasCode(diags, Code::AbsoluteExtrusionUnsupported));
        CHECK(diags.hasErrors());
    }

    SECTION("absence of both is rejected, not assumed safe") {
        // Firmware defaults to absolute when unspecified, so silence is not consent.
        DiagnosticList diags;
        const auto r = scanText(";HEIGHT:0.2\nG1 X1 E1\n; PRINT_END\n", diags);
        CHECK(r.extrusionMode == ExtrusionMode::Unknown);
        CHECK(hasCode(diags, Code::ExtrusionModeUnknown));
    }

    SECTION("the first mode command wins") {
        DiagnosticList diags;
        const auto r = scanText("M83\nM82\n;HEIGHT:0.2\nG1 X1 E1\n; PRINT_END\n", diags);
        CHECK(r.extrusionMode == ExtrusionMode::Relative);
    }

    SECTION("similar tokens do not match") {
        // M831 is not M83, and a comment mentioning M83 is not a command.
        DiagnosticList diags;
        const auto r = scanText("M831\n; remember to set M83\n;HEIGHT:0.2\n"
                                "G1 X1 E1\n; PRINT_END\n", diags);
        CHECK(r.extrusionMode == ExtrusionMode::Unknown);
    }
}

TEST_CASE("already-processed files are rejected", "[scanner][precondition]")
{
    SECTION("our own marker") {
        DiagnosticList diags;
        const auto r = scanText(
            std::string(kProcessedMarker) + " 2.0.0\nM83\n;HEIGHT:0.2\n"
            "G1 X1 E1\n; PRINT_END\n",
            diags);
        CHECK(r.alreadyProcessed);
        CHECK(hasCode(diags, Code::AlreadyProcessed));
    }

    SECTION("the legacy tool's marker") {
        // A file produced by the old Delphi application must also be refused, or its
        // adjustments would be compounded by ours.
        DiagnosticList diags;
        const auto r = scanText(
            "; Edited by SB53 G-Code Flow/Temperature Controller  -V1.1-\n"
            "M83\n;HEIGHT:0.2\nG1 X1 E1\n; PRINT_END\n",
            diags);
        CHECK(r.alreadyProcessed);
        CHECK(hasCode(diags, Code::AlreadyProcessed));
    }
}

TEST_CASE("slicer identity is read from the config block after the body", "[scanner][ids]")
{
    // OrcaSlicer writes these AFTER "; EXECUTABLE_BLOCK_END", not in the header, so the
    // scan cannot stop once the body is bounded.

    DiagnosticList diags;
    const auto r = scanText(kMinimal, diags);

    CHECK(r.filamentType == "PLA");
    CHECK(r.printerSettingsId == "AWD V0 @ 0.4 nozzle");

    // Surrounding quotes are OrcaSlicer's escaping, not part of the profile name.
    CHECK(r.filamentSettingsId == "Elegoo HS PLA+ awd hott");
}

TEST_CASE("comment value parsing tolerates spacing and rejects near-misses", "[scanner][parse]")
{
    using detail::commentValue;

    CHECK(commentValue("; filament_type = PLA", "filament_type") == "PLA");
    CHECK(commentValue(";filament_type=PLA", "filament_type") == "PLA");
    CHECK(commentValue(";   filament_type   =   PLA  ", "filament_type") == "PLA");
    CHECK(commentValue("; k = \"quoted value\"", "k") == "quoted value");

    // A key that merely starts with ours must not match.
    CHECK_FALSE(commentValue("; filament_type_extra = X", "filament_type").has_value());
    // Not a comment.
    CHECK_FALSE(commentValue("G1 X1 filament_type = PLA", "filament_type").has_value());
    // No separator.
    CHECK_FALSE(commentValue("; filament_type PLA", "filament_type").has_value());
}

TEST_CASE("malformed input produces specific, actionable errors", "[scanner][errors]")
{
    SECTION("empty file") {
        DiagnosticList diags;
        scanText("", diags);
        CHECK(hasCode(diags, Code::FileEmpty));
    }

    SECTION("no body markers at all") {
        DiagnosticList diags;
        scanText("M83\nG1 X1 E1\n", diags);
        CHECK(hasCode(diags, Code::PrintBodyNotFound));
    }

    SECTION("body starts but never ends") {
        // Distinguished from the above because the user's fix differs: here they need
        // an end marker in their custom end G-code.
        DiagnosticList diags;
        const auto r = scanText("M83\n;HEIGHT:0.2\nG1 X1 E1\n", diags);
        CHECK(r.bodyFirstLine == 2);
        CHECK(r.bodyLastLine == 0);
        CHECK(hasCode(diags, Code::PrintBodyNotFound));
    }
}

TEST_CASE("CRLF input and a UTF-8 BOM are handled", "[scanner][parse]")
{
    DiagnosticList diags;
    const auto r = scanText(
        "\xEF\xBB\xBF; HEADER_BLOCK_START\r\nM83\r\n;HEIGHT:0.25\r\n"
        "G1 X1 E1\r\n; EXECUTABLE_BLOCK_END\r\n",
        diags);

    CHECK_FALSE(diags.hasErrors());
    CHECK(r.extrusionMode == ExtrusionMode::Relative);
    CHECK(r.bodyFirstLine == 3);
    CHECK(r.bodyLastLine == 4);
}

// ---------------------------------------------------------------------------
// Against the real fixtures
// ---------------------------------------------------------------------------

TEST_CASE("scanner handles real OrcaSlicer output", "[scanner][fixture]")
{
    const std::filesystem::path dir{SB53_TESTDATA_DIR};

    SECTION("unprocessed benchy") {
        std::ifstream in{dir / "fixtures" / "orca-basic.gcode"};
        REQUIRE(in);

        DiagnosticList diags;
        const auto r = GcodeScanner::scan(in, diags);

        INFO("diagnostics: " << (diags.items().empty() ? "none"
                                                       : diags.items().front().message));
        CHECK_FALSE(diags.hasErrors());
        CHECK(r.extrusionMode == ExtrusionMode::Relative);
        CHECK_FALSE(r.alreadyProcessed);
        CHECK(r.hasPrintBody());

        // Verified by hand against the file: M83 at 270, first ;HEIGHT: at 275,
        // "; EXECUTABLE_BLOCK_END" at 2275.
        CHECK(r.bodyFirstLine == 275);
        CHECK(r.bodyLastLine == 2274);

        CHECK(r.filamentType == "PLA");
        CHECK(r.filamentSettingsId == "Elegoo HS PLA+ awd hott");
        CHECK(r.printerSettingsId == "AWD V0 @ 0.4 nozzle");
    }

    SECTION("arc-heavy variant scans identically") {
        std::ifstream in{dir / "fixtures" / "orca-arcs.gcode"};
        REQUIRE(in);

        DiagnosticList diags;
        const auto r = GcodeScanner::scan(in, diags);

        // Arcs affect the estimator, not the scan.
        CHECK_FALSE(diags.hasErrors());
        CHECK(r.extrusionMode == ExtrusionMode::Relative);
        CHECK(r.hasPrintBody());
    }

    SECTION("legacy-processed file is refused") {
        std::ifstream in{dir / "fixtures" / "legacy-processed.gcode"};
        REQUIRE(in);

        DiagnosticList diags;
        const auto r = GcodeScanner::scan(in, diags);

        CHECK(r.alreadyProcessed);
        CHECK(hasCode(diags, Code::AlreadyProcessed));
        CHECK(diags.hasErrors());
    }
}
